import type { Metadata } from "next";
import { nunito } from '@/app/ui/fonts';
import "./globals.css";
import Link from "next/link";
import Navbar from "@/components/navbar/Navbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased mx-8`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}



